services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: crazy8-backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    container_name: crazy8-frontend
